---
fullname: mathcomp-extra
shortname: mathcomp-extra
organization: thery
community: false
dune: false
action: true

synopsis: Some extra material for mathcomp

description: |-

  Some extra material for mathcomp

    [Fibonacci and Lucas numbers](./fib.v)

    [Lower bound of lcm(1, 2, ..., n)](./lcm_lbound.v)

    [Definitions and some properties of matroids](./matroid.v)

    [Rsa algorithm](./rsa.v)

    [More lemmas about polynomials](./more_thm.v)

    [Polynomials modulo](./divpoly.v)

    [Binary gcd](./bgcdn.v)

    [Nth root for natural number](./rootn.v)

    [The aks algorithm](./aks_algo.v)  the algorithm as in Hing Lun Chan's PhD thesis
 
    [The aks correctness proof](./aks.v)  a transcription of Hing Lun Chan's proof
 
    [The proof of Lucas theorem for binomial](./digitn.v)

    [A formalisation of 2-player games](./tplayer.v) (in progress)

    [A formalisation of Fast Fourier Transform](./fft.v)

    [More theorems about tuples](./more_tuple.v)

    [A formalisation of sorting network](./nsort.v)
    
    [A formalisation of bitonic sort](./bitonic.v) 
    
    [A formalisation of Batcher odd or even sort](./batcher.v) 
    
    [A formalisation of Knuth exchange sort](./bjsort.v) 
 
    [A fun puzzle about a tricky integer function](./puzzleFF.v)

    [A port to mathcomp of the elliptic curve of CoqPrime](./elliptic.v)

    [A formalisation of some sudoku solvers ](./sudoku.v)
   
    [A formalisation of Montgomery reduction ](./montgomery.v)

    [A formalisation of Residue Number System](./rns.v)
    
    [Euler Criterion](./euler.v)

    [Trivial fact about the ultra hex number](./ultrahex.v)
    

  A note about sorting network is available [here](https://hal.inria.fr/hal-03585618).

authors:
- name: Laurent Théry

maintainers:
- name: Laurent Théry
  nickname: thery

opam-file-maintainer: thery@sophia.inria.fr

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: '8.18 or later'
  opam: '{(>= "8.18")}'

dependencies:
- opam:
    name: coq-hierarchy-builder
    version: '{(>= "1.8.0")}'
  description: |- 
    [ Hierarchy Builder 1.8.0 or later](https://github.com/math-comp/hierarchy-builder)
- opam:
    name: coq-mathcomp-ssreflect
    version: '{(>= "2.3.0")}'
  description: |-
    [MathComp ssreflect 2.2.0 or later](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-fingroup
    version: '{(>= "2.3.0")}'
  description: |-
    [MathComp fingroup 2.2.0 or later](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-algebra
    version: '{(>= "2.3.0")}'
  description: |-
    [MathComp algebra 2.3.0 or later](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-field
    version: '{(>= "2.3.0")}'
  description: |-
    [MathComp field 2.3.0 or later](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-zify
    version: '{(>= "1.5.0+2.0+8.16")}'
  description: |-
    [MathComp zify 1.5.0+2.0+8.16 or later](https://github.com/math-comp/mczify)
- opam:
    name: coq-mathcomp-algebra-tactics
    version: '{(>= "1.2.3")}'
  description: |-
    [MathComp Algebra Tactics 1.2.3 or later](https://github.com/math-comp/algebra-tactics)

tested_coq_opam_versions:
- version: '2.3.0-coq-8.19'
  repo: 'mathcomp/mathcomp'

namespace: mathcomp-extra

keywords:
- name: mathcomp extra


---
