---
fullname: mathcomp-extra
shortname: mathcomp-extra
organization: thery
community: false
dune: false
action: true

synopsis: Some extra material for mathcomp

description: |-

  Some extra material for mathcomp

    [Fibonacci and Lucas numbers](./fib.v)

    [Lower bound of lcm(1, 2, ..., n)](./lcm_lbound.v)

    [Definitions and some properties of matroids](./matroid.v)

    [Rsa algorithm](./rsa.v)

    [More lemmas about polynomials](./more_thm.v)

    [Polynomials modulo](./divpoly.v)

    [Binary gcd](./bgcdn.v)

    [Nth root for natural number](./rootn.v)

    [The aks algorithm](./aks_algo.v)  the algorithm as in Hing Lun Chan's PhD thesis
 
    [The aks correctness proof](./aks.v)  a transcription of Hing Lun Chan's proof
 
    [The proof of Lucas theorem for binomial](./digitn.v)

    [A formalisation of 2-player games](./tplayer.v) (in progress)

    [A formalisation of Fast Fourier Transform](./fft.v)

    [More theorems about tuples](./more_tuple.v)

    [A formalisation of sorting network](./nsort.v)
    
    [A formalisation of bitonic sort](./bitonic.v) 
    
    [A formalisation of Batcher odd or even sort](./batcher.v) 
    
    [A formalisation of Knuth exchange sort](./bjsort.v) 
 
    [A fun puzzle about a tricky integer function](./puzzleFF.v)

    [A port to mathcomp of the elliptic curve of CoqPrime](./elliptic.v)

    [A formalisation of some sudoku solvers ](./sudoku.v)
   
    [A formalisation of Montgomery reduction ](./montgomery.v)

    [A formalisation of Residue Number System](./rns.v)
    
    [Euler Criterion](./euler.v)

    [Trivial fact about the ultra hex number](./ultrahex.v)
    
    [Some facts about addition chain](./chain.v)

    [Definition of cycles from list in permutation](./lcycle.v)
    
    [The last digit of n^5 is the same than the one of n](./power5.v)

    [Definition of factorions and how many there are](./factorion.v)

    [Definition of circular primes and some properties](./cprime.v)

    [All prime numbers (except 2 and 3) are next to a multiple of 6](./prime6.v)

    [Nicomachus Theorem about summation of cube](./nicomachus.v)

    [Liouville Theorem about number's divisors](./liouville.v)

    [Square numbers ending with xyxyxyxyxy](./repeatxy.v)
    
    [Binomial equation about taking 2 segments from n points](./binception.v)

  A note about sorting network is available [here](https://hal.inria.fr/hal-03585618).

  A note about addition chain is available [here](https://hal.science/hal-04971933).

  A note about factorions is available [here](https://inria.hal.science/hal-05265618).

authors:
- name: Laurent Théry

maintainers:
- name: Laurent Théry
  nickname: thery

opam-file-maintainer: thery@sophia.inria.fr

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: '9.1 or later'
  opam: '{(>= "9.1")}'

dependencies:
- opam:
    name: rocq-mathcomp-boot
    version: '{(>= "2.5.0")}'
  description: |-
    [MathComp boot 2.5.0 or later](https://math-comp.github.io)
- opam:
    name: rocq-mathcomp-fingroup
    version: '{(>= "2.5.0")}'
  description: |-
    [MathComp fingroup 2.5.0 or later](https://math-comp.github.io)
- opam:
    name: rocq-mathcomp-algebra
    version: '{(>= "2.5.0")}'
  description: |-
    [MathComp algebra 2.5.0 or later](https://math-comp.github.io)
- opam:
    name: rocq-mathcomp-field
    version: '{(>= "2.5.0")}'
  description: |-
    [MathComp field 2.5.0 or later](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-zify
    version: '{(>= "1.6.0+2.3+8.18")}'
  description: |-
    [MathComp zify 1.6.0+2.3+8.18 or later](https://github.com/math-comp/mczify)
- opam:
    name: coq-mathcomp-algebra-tactics
    version: '{(>= "1.2.7")}'
  description: |-
    [MathComp Algebra Tactics 1.2.7 or later](https://github.com/math-comp/algebra-tactics)

tested_coq_opam_versions:
- version: '2.5.0-rocq-prover-9.1'
  repo: 'mathcomp/mathcomp'

namespace: mathcomp-extra

keywords:
- name: mathcomp extra


---
